# Generated by Django 4.0.2 on 2022-03-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_alter_company_clogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cLogo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
