# Generated by Django 4.0.2 on 2022-03-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_alter_company_clogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='cLogo',
            new_name='companyLogo',
        ),
    ]
