# Generated by Django 4.0.2 on 2022-03-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('approved', 'approved'), ('on_progress', 'on_progress'), ('tested', 'tested'), ('completed', 'completed')], default='status', max_length=50),
        ),
    ]
