# Generated by Django 4.0.2 on 2022-03-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0006_project_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyLogo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
