# Generated by Django 4.0.2 on 2022-04-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0007_alter_company_companylogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empregistraion',
            fields=[
                ('First_name', models.CharField(max_length=50, primary_key='true', serialize=False, unique='true')),
                ('Last_name', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_phoneno', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('re_password', models.CharField(max_length=50)),
            ],
        ),
    ]
